-- Stored Marktplaats ad text per stove, generated by the app when a stove is added or edited,
-- and the editable prompt used to generate it. Both are additive; existing code ignores them.

-- marketplace_ad_edited: the text was changed by hand, so edits to the stove no longer regenerate it.
-- marketplace_ad_outdated: the stove was edited after that manual change; the text needs checking.
alter table public.stoves
  add column marketplace_ad text check (char_length(marketplace_ad) <= 10000),
  add column marketplace_ad_edited boolean not null default false,
  add column marketplace_ad_outdated boolean not null default false;

-- The existing "stoves update" policy limits updates to team members.
grant update (marketplace_ad, marketplace_ad_edited, marketplace_ad_outdated) on public.stoves to authenticated;

-- The ad prompt. A single row, like company_settings. The app falls back to its built-in
-- default prompt while this row does not exist.
create table public.ad_settings (
  id boolean primary key default true check (id),
  prompt text not null check (char_length(prompt) between 1 and 4000),
  updated_at timestamptz not null default now()
);

alter table public.ad_settings enable row level security;
revoke all on public.ad_settings from anon, authenticated;
grant select, insert, update on public.ad_settings to authenticated;

create policy "ad_settings select" on public.ad_settings for select to authenticated
  using ((select public.is_team_member()));
create policy "ad_settings insert" on public.ad_settings for insert to authenticated
  with check ((select public.is_team_member()));
create policy "ad_settings update" on public.ad_settings for update to authenticated
  using ((select public.is_team_member()))
  with check ((select public.is_team_member()));
