-- Six-digit stove numbers: existing stoves move from 1001, 1002, ... to 100001, 100002, ...
-- and new stoves continue after the highest number.

-- Existing photos keep their storage path ("1001/<uuid>.jpg"): objects cannot be moved from SQL.
-- The path is only a storage key, so the rule tying it to the stove number is dropped.
do $$
declare
  path_check text;
begin
  select conname into strict path_check
  from pg_constraint
  where conrelid = 'public.stove_photos'::regclass and contype = 'c';

  execute format('alter table public.stove_photos drop constraint %I', path_check);
end
$$;

alter table public.stove_photos drop constraint stove_photos_stove_number_fkey;

alter table public.stoves alter column number set generated by default;
update public.stoves set number = number + 99000 where number < 100000;
update public.stove_photos set stove_number = stove_number + 99000 where stove_number < 100000;
alter table public.stoves alter column number set generated always;

alter table public.stove_photos
  add constraint stove_photos_stove_number_fkey
  foreign key (stove_number) references public.stoves (number) on delete cascade;

alter table public.stoves add constraint stoves_number_six_digits check (number between 100000 and 999999);

select setval(
  pg_get_serial_sequence('public.stoves', 'number'),
  greatest((select max(number) from public.stoves), 100000)
);
