-- Stoves imported from the WooCommerce shop keep their five-digit shop number (e.g. 26118), which
-- is also on the stove itself. Stoves added in the app still get the next six-digit number.

alter table public.stoves alter column number set generated by default;

alter table public.stoves drop constraint stoves_number_six_digits;
alter table public.stoves add constraint stoves_number_range check (number between 10000 and 999999);

-- An explicit six-digit number could collide with a number the sequence hands out later, so
-- explicit numbers are limited to the five-digit shop range. With "generated by default" the
-- sequence value is filled in before this trigger runs; it is never above the sequence's last value.
create function public.check_stove_number()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.number >= 100000
     and new.number > coalesce(pg_sequence_last_value(pg_get_serial_sequence('public.stoves', 'number')::regclass), 0) then
    raise exception 'Stove numbers of six digits are assigned automatically'
      using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

revoke execute on function public.check_stove_number() from public, anon, authenticated;

create trigger stoves_check_number
  before insert on public.stoves
  for each row execute function public.check_stove_number();

-- The import sets the shop number and links the existing shop product.
grant insert (number, shop_product_id) on public.stoves to authenticated;
